### 1. What is a boxplot?


A boxplot is a data visualization of the minimum, maximum and interquartile range for variables and also outlier detection.

### 2. Using the mtcars data set, what is the mean and standard deviation values for the qsec variable?

In [4]:
import pandas as pd
import numpy as np

In [16]:
address = 'C:/Users.../Ex_Files_Python_Data_Science_EssT_Pt_1/Exercise Files/Data/mtcars.csv'

cars = pd.read_csv(address)

In [10]:
cars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [12]:
cars.qsec.describe()

count    32.000000
mean     17.848750
std       1.786943
min      14.500000
25%      16.892500
50%      17.710000
75%      18.900000
max      22.900000
Name: qsec, dtype: float64

### 3.What does the describe function generate?

The describe function generates the descriptive statistics for all of the variables in a dataset.

### 4. What is the result of the multiplication of the 2x2 matrices a=np.array([[1.,3.],[2.,4.]]) and b=np.array([[5.,8.],[7.,9.]])?

In [9]:
a=np.array([[1.,3.],[2.,4.]])
b=np.array([[5.,8.],[7.,9.]])
a*b

array([[ 5., 24.],
       [14., 36.]])

### 5. What is the dot product of x=np.array([1,2,7]) and y=np.array([3,8,9])?

In [10]:
x=np.array([1,2,7])
y=np.array([3,8,9])
np.dot(x,y)

82

### 6.What is the matrix multiplication of the 2x2 matrices xx=np.array([[7.,9.],[5.,12.]]) and yy=np.array([[2.,8.],[7.,4.]])?

In [11]:
xx=np.array([[7.,9.],[5.,12.]])
yy=np.array([[2.,8.],[7.,4.]])
np.dot(xx,yy)

array([[77., 92.],
       [94., 88.]])

### 7. What is the matrix multiplication of the 2x3 matrix xx=np.array([[1.,2.,3.],[4.,5.,6.]]) and the 3x2 matrix yy=np.array([[10.,11.],[20.,21.],[30.,31.]])?

In [12]:
xx=np.array([[1.,2.,3.],[4.,5.,6.]])
yy=np.array([[10.,11.],[20.,21.],[30.,31.]])
np.dot(xx,yy)

array([[140., 146.],
       [320., 335.]])

### 8.What is a matrix?
a two-dimensional container for elements that are stored in an array


### 9. Let the array a and b be given by a=np.array([1,8,2,6,3,8,5,5,5,5])' and 'b=np.array([17,16,20,18,22,15,21,15,17,22]). What is the result of (a+b)/10?

In [14]:
a=np.array([1,8,2,6,3,8,5,5,5,5])
b=np.array([17,16,20,18,22,15,21,15,17,22])
(a+b)/10

array([1.8, 2.4, 2.2, 2.4, 2.5, 2.3, 2.6, 2. , 2.2, 2.7])

### 10. Given a=np.array([10, 15, 20]) and b=([5, 7, 9]), what is the result of (a-b)*7?

In [15]:
a=np.array([10, 15, 20])
b=([5, 7, 9])
(a-b)*7

array([35, 56, 77])

### 11.What is the code to isolate the data from the target variable gathering the values only, given the sample dataset df_best containing 4 variables?
data=df_best.iloc[:,0:3].values target=df_best.iloc[:,3].values
<br>
This code isolates the data from the target variable and returns the values only.

In [20]:
data = cars.iloc[:,0:3].values
data

array([['Mazda RX4', 21.0, 6],
       ['Mazda RX4 Wag', 21.0, 6],
       ['Datsun 710', 22.8, 4],
       ['Hornet 4 Drive', 21.4, 6],
       ['Hornet Sportabout', 18.7, 8],
       ['Valiant', 18.1, 6],
       ['Duster 360', 14.3, 8],
       ['Merc 240D', 24.4, 4],
       ['Merc 230', 22.8, 4],
       ['Merc 280', 19.2, 6],
       ['Merc 280C', 17.8, 6],
       ['Merc 450SE', 16.4, 8],
       ['Merc 450SL', 17.3, 8],
       ['Merc 450SLC', 15.2, 8],
       ['Cadillac Fleetwood', 10.4, 8],
       ['Lincoln Continental', 10.4, 8],
       ['Chrysler Imperial', 14.7, 8],
       ['Fiat 128', 32.4, 4],
       ['Honda Civic', 30.4, 4],
       ['Toyota Corolla', 33.9, 4],
       ['Toyota Corona', 21.5, 4],
       ['Dodge Challenger', 15.5, 8],
       ['AMC Javelin', 15.2, 8],
       ['Camaro Z28', 13.3, 8],
       ['Pontiac Firebird', 19.2, 8],
       ['Fiat X1-9', 27.3, 4],
       ['Porsche 914-2', 26.0, 4],
       ['Lotus Europa', 30.4, 4],
       ['Ford Pantera L', 15.8, 8],
       ['Ferrari

In [22]:
target = cars.iloc[:,3].values
target

array([160. , 160. , 108. , 258. , 360. , 225. , 360. , 146.7, 140.8,
       167.6, 167.6, 275.8, 275.8, 275.8, 472. , 460. , 440. ,  78.7,
        75.7,  71.1, 120.1, 318. , 304. , 350. , 400. ,  79. , 120.3,
        95.1, 351. , 145. , 301. , 121. ])

### 12. What does the hue parameter represent in seaborn's pairplot function?
the categorical variable used to plot the aspects in different colors
<br>

For multivariate outlier detection hue represents the categorical variable used to plot the aspects in different colors.

### 13.What is Tukey's rule for outlier detection?
A variable is suspicious of having outliers if it has values that are below Q1-(1.5)IQR or above Q3+(1.5)IQR.
<br>

Tukey's rule is used to detect potential outliers for a variable to see if there are any values that fall below Q1-(1.5)IQR or above Q3+(1.5)IQR.

### 14.What does the the range of values change to once a variable that ranges from 5 to 30 is scaled?
after being scaled the actual values range from 0 and 1
<br>

Scaling keeps the distribution of values the same but the actual values changes to range between 0 and 1, by default.

### 15.What is the lower and upper limit for the Tukey Outlier, given Q1= 1.714 and Q3=1.936?
lower limit=1.381 upper limit=2.269
<br>

The lower and upper limit equations for the Tukey Outlier are Q1-(1.5)IQR and Q3+(1.5)IQR.<br>
IQR = Q3 - Q1 = 1.936 - 1.714 = 0.222<br>
1.5 * IQR = 1.5 * 0.222 = 0.333<br>
lower limit = 1.714 - 0.333 = 1.381<br>
upper limit = 1.936 + 0.333 = 2.269

### 16. Write the code that would be used to standardize the variable, environmental, from a sample data set?
standardized_environmental=scale(environmental)
<br>

Using the scale function without any arguments gives the environmental variable a standard normal distribution.

### 17.What is the difference between normalization and standardization?
Normalization puts each observation on a relative scale between 0 and 1 and standardization rescales data so that it has a zero mean and unit variance.
<br>

Normalization and standardization by default changes actual values to fall between 0 and 1 and rescales data to have a zero mean and unit variance, respectively.


### 18. What is the chi-squared results from the comparison of two variables, given a chi-square of 3.171 with a corresponding p-value of 0.205?
fail to reject the null hypothesis and conclude that the variables are independent of one another
<br>

We fail to reject the null hypothesis and conclude that the variables are independent of one another because p>0.05.

### 19. What is the chi-squared results from the comparison of two variables, given a chi-square of 11.1304 with a corresponding p-value of 0.0008?
reject the null hypothesis and conclude that the variables are correlated
<br>

We reject the null hypothesis and conclude that the variables are correlated because p<0.05.

### 20. What is a chi-squared test?
a test for independence to determine if nonlinear variables are independent of one other
<br>

This is the definition of a chi-squared test.

### 25.Using the mtcars data set, how many V-shaped engines have 6 cylinders?
vs represents a V-engine (0) or straight engine (1)

In [38]:
pd.crosstab(cars['cyl'], cars['vs'])

vs    0   1
cyl        
4     1  10
6     3   4
8    14   0

### 26. Using the mtcars dataset, what is the results from the crosstab of the variables vs and cyl?
cars with a v-shaped engine mostly have 8 cylinders and cars with a straight engine mostly have 4 cylinders

